apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  serviceName: "mysql"
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
        - name: mysql
          image: acavinash/mysql:v1
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
  # this is PVC directly. It will be created dynamically using StorageClass
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  clusterIP: None
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
